### ISSUE TITLE
Usage with SwiftUI

### ISSUE THREAD

**Issue by Vincz** [iSapozhnik/Menu#19]
Hi! The library looks really great. I was wondering if it is possible to use it with SwiftUI?
If so, would you have an example?
I tried using `NSViewControllerRepresentable` but without success. I'd only like to attach the Menu to a SwiftUI View (the click and the position). 
Any idea? Thanks!

**Comment by iSapozhnik** [comment]
Hey! Unfortunately I'm not that good at SwiftUI so can't really help here. Sorry!
